// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Include your device-specific headers, and edit functions below
// #include "hal.h"

#include "mongoose_glue.h"
#include "Arduino.h"

// added these forward declarations so that btn functions can access s_*_settings
static struct comms_settings s_comms_settings;
static struct input_settings s_input_settings;
static struct misc_settings s_misc_settings;

void glue_init(void) {
  MG_DEBUG(("Custom init done"));
}

// This function is called automatically every WIZARD_WEBSOCKET_TIMER_MS millis
void glue_websocket_on_timer(struct mg_connection *c) {
  uint64_t *timer_work = (uint64_t *) &c->data[0];  // Beware: c->data size is MG_DATA_SIZE
  uint64_t *timer_1s = (uint64_t *) &c->data[sizeof(uint64_t)];
  uint64_t now = mg_millis();

  // Send updates to websocket work widgets value every 50 milliseconds
  if (mg_timer_expired(timer_work, 50, now) || s_misc_settings.update) {
    s_misc_settings.update = false;
    mg_ws_printf(c, WEBSOCKET_OP_TEXT, "{%m: %d}", MG_ESC("steer_state"), s_input_settings.steer_state);
    mg_ws_printf(c, WEBSOCKET_OP_TEXT, "{%m: %d}", MG_ESC("work_state"), s_input_settings.work_state);
    mg_ws_printf(c, WEBSOCKET_OP_TEXT, "{%m: %d}", MG_ESC("work_input"), s_input_settings.work_input);
    mg_ws_printf(c, WEBSOCKET_OP_TEXT, "{%m: %d}", MG_ESC("work_thres"), s_input_settings.work_thres);
    mg_ws_printf(c, WEBSOCKET_OP_TEXT, "{%m: %d}", MG_ESC("kickout_state"), s_input_settings.kickout_state);
  }

  if (mg_timer_expired(timer_1s, 1000, now)) {
    const char* ko_help_1 = "Set AOG to Count/Pressure/Current Sensor according to your setup";
    const char* ko_help_2 = "Set AOG to \"Count Sensor\". Connect both signals, one to each Kickout Input (Analog & Digital)";
    const char* ko_help_3 = "Set AOG to \"Pressure Sensor\". Connect to Kickout Analog (Fastest response time)";
    const char* ko_help_4 = "Set AOG to \"Pressure Sensor\". *Need more instructions*";
    const char* ko_help_5 = "Set AOG to \"Pressure Sensor\". *Need more instructions*";
    const char* ko_help_selected = "Unknown option";

    // check first char of dropdown's selected option to match displayed help text
    if (s_input_settings.kickout_mode[0] == '1') ko_help_selected = ko_help_1;
    else if (s_input_settings.kickout_mode[0] == '2') ko_help_selected = ko_help_2;
    else if (s_input_settings.kickout_mode[0] == '3') ko_help_selected = ko_help_3;
    else if (s_input_settings.kickout_mode[0] == '4') ko_help_selected = ko_help_4;
    else if (s_input_settings.kickout_mode[0] == '5') ko_help_selected = ko_help_5;

    //MG_INFO((s_input_settings.kickout_mode));
    mg_ws_printf(c, WEBSOCKET_OP_TEXT, "{%m: %m}", MG_ESC("kickout_dropdown_help"), MG_ESC((ko_help_selected)));
  }
}

// save_ip
static uint64_t s_action_timeout_save_ip;  // Time when save_ip ends
bool glue_check_save_ip(void) {
  return s_action_timeout_save_ip > mg_now(); // Return true if save_ip is in progress
}
void glue_start_save_ip(void) {
  s_action_timeout_save_ip = mg_now() + 250; // Start save_ip, finish after 250ms
  MG_INFO(("Save IP"));
}

// reboot
static uint64_t s_action_timeout_reboot;  // Time when reboot ends
bool glue_check_reboot(void) {
  return s_action_timeout_reboot > mg_now(); // Return true if reboot is in progress
}
void glue_start_reboot(void) {
  s_action_timeout_reboot = mg_now() + 1000; // Start reboot, finish after 1 second
  SCB_AIRCR = 0x05FA0004; // Teensy reboot
}

// dec_work_thres
static uint64_t s_action_timeout_dec_work_thres;  // Time when dec_work_thres ends
bool glue_check_dec_work_thres(void) {
  return s_action_timeout_dec_work_thres > mg_now(); // Return true if dec_work_thres is in progress
}
void glue_start_dec_work_thres(void) {
  s_action_timeout_dec_work_thres = mg_now() + 100; // Start dec_work_thres, finish after 1 second
  if(s_input_settings.work_thres > 10) s_input_settings.work_thres -= 1;
  glue_update_state();
}

// set_work_thres
static uint64_t s_action_timeout_set_work_thres;  // Time when set_work_thres ends
bool glue_check_set_work_thres(void) {
  return s_action_timeout_set_work_thres > mg_now(); // Return true if set_work_thres is in progress
}
void glue_start_set_work_thres(void) {
  s_action_timeout_set_work_thres = mg_now() + 250; // Start set_work_thres, finish after 250ms
  //s_input_settings.work_thres = min(max(s_input_settings.work_input, 10), 90);
  s_input_settings.work_thres = constrain(s_input_settings.work_input, 10, 90);
  glue_update_state();
}

// inc_work_thres
static uint64_t s_action_timeout_inc_work_thres;  // Time when inc_work_thres ends
bool glue_check_inc_work_thres(void) {
  return s_action_timeout_inc_work_thres > mg_now(); // Return true if inc_work_thres is in progress
}
void glue_start_inc_work_thres(void) {
  s_action_timeout_inc_work_thres = mg_now() + 100; // Start inc_work_thres, finish after 1 second
  if(s_input_settings.work_thres < 90) s_input_settings.work_thres += 1;
  glue_update_state();
}

// set_work_digital
static uint64_t s_action_timeout_set_work_digital;  // Time when set_work_digital ends
bool glue_check_set_work_digital(void) {
  return s_action_timeout_set_work_digital > mg_now(); // Return true if set_work_digital is in progress
}
void glue_start_set_work_digital(void) {
  s_action_timeout_set_work_digital = mg_now() + 250; // Start set_work_digital, finish after 250ms
  s_input_settings.work_thres = 50;
  memcpy(s_input_settings.work_hyst, "18", 2);
  s_input_settings.work_invert = true;
  glue_update_state();
}

// firmware_update
void  *glue_ota_begin_firmware_update(char *file_name, size_t total_size) {
  bool ok = mg_ota_begin(total_size);
  MG_DEBUG(("%s size %lu, ok: %d", file_name, total_size, ok));
  return ok ? (void *) 1 : NULL;
}
bool  glue_ota_end_firmware_update(void *context) {
  bool ok = mg_ota_end();
  MG_DEBUG(("ctx: %p, success: %d", context, ok));
  return ok;
}
bool  glue_ota_write_firmware_update(void *context, void *buf, size_t len) {
  MG_DEBUG(("ctx: %p %p/%lu", context, buf, len));
  return mg_ota_write(buf, len);
}

static struct comms_settings s_comms_settings = {192, 168, 5, 126, "60ms - F9P", false};
void glue_get_comms_settings(struct comms_settings *data) {
  *data = s_comms_settings;  // Sync with your device
}
void glue_set_comms_settings(struct comms_settings *data) {
  s_comms_settings = *data; // Sync with your device
}

static struct input_settings s_input_settings = {false, false, 0, 50, "18", 18, true, false, "#f064f0", "1 - AOG Setting (default)"};
void glue_get_input_settings(struct input_settings *data) {
  *data = s_input_settings;  // Sync with your device
}
void glue_set_input_settings(struct input_settings *data) {
  s_input_settings = *data; // Sync with your device
}

static struct misc_settings s_misc_settings = {false, "AiO GUI v5.old"};
void glue_get_misc_settings(struct misc_settings *data) {
  *data = s_misc_settings;  // Sync with your device
}
void glue_set_misc_settings(struct misc_settings *data) {
  s_misc_settings = *data; // Sync with your device
}