// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Include your device-specific headers, and edit functions below
// #include "hal.h"

#include "mongoose_glue.h"

// Iterate over all websocket connections and write JSON message to them
static void ws_voltage_timer(void *arg) {
  struct mg_mgr *mgr = (struct mg_mgr *) arg;
  struct mg_connection *c;

  uint64_t now = mg_millis();

  for (c = mgr->conns; c != NULL; c = c->next) {
    if (c->is_websocket) {
      // Prevent stale connections to grow infinitely
      if (c->send.len > 2048) continue;

      mg_ws_printf(c, WEBSOCKET_OP_TEXT, "{%m: %llu, %m: %s}",
                   MG_ESC("voltage"), now % 1000,  // Simulate voltage
                   MG_ESC("led"), now & 1 ? "true" : "false"  // Simulate LED
      );
    }
  }
}

void glue_init(void) {
  MG_INFO(("Starting websocket timers"));

  mg_timer_add(&g_mgr, 200,       // Call every 200 milliseconds
               MG_TIMER_REPEAT,   // Periodically
               ws_voltage_timer,  // This function
               &g_mgr             // And pass this parameter to the function
  );

  MG_DEBUG(("Custom init done"));
}
static uint64_t s_action_timeout_reboot;  // Time when reboot ends
bool glue_check_reboot(void) {
  return s_action_timeout_reboot > mg_now(); // Return true if reboot is in progress
}
void glue_start_reboot(void) {
  s_action_timeout_reboot = mg_now() + 1000; // Start reboot, finish after 1 second
}

static uint64_t s_action_timeout_dec_work_thres;  // Time when dec_work_thres ends
bool glue_check_dec_work_thres(void) {
  return s_action_timeout_dec_work_thres > mg_now(); // Return true if dec_work_thres is in progress
}
void glue_start_dec_work_thres(void) {
  s_action_timeout_dec_work_thres = mg_now() + 1000; // Start dec_work_thres, finish after 1 second
}

static uint64_t s_action_timeout_inc_work_thres;  // Time when inc_work_thres ends
bool glue_check_inc_work_thres(void) {
  return s_action_timeout_inc_work_thres > mg_now(); // Return true if inc_work_thres is in progress
}
void glue_start_inc_work_thres(void) {
  s_action_timeout_inc_work_thres = mg_now() + 1000; // Start inc_work_thres, finish after 1 second
}

static uint64_t s_action_timeout_set_work_thres;  // Time when set_work_thres ends
bool glue_check_set_work_thres(void) {
  return s_action_timeout_set_work_thres > mg_now(); // Return true if set_work_thres is in progress
}
void glue_start_set_work_thres(void) {
  s_action_timeout_set_work_thres = mg_now() + 1000; // Start set_work_thres, finish after 1 second
}

static uint64_t s_action_timeout_set_work_digital;  // Time when set_work_digital ends
bool glue_check_set_work_digital(void) {
  return s_action_timeout_set_work_digital > mg_now(); // Return true if set_work_digital is in progress
}
void glue_start_set_work_digital(void) {
  s_action_timeout_set_work_digital = mg_now() + 1000; // Start set_work_digital, finish after 1 second
}

void *glue_ota_begin_firmware_update(char *file_name, size_t total_size) {
  bool ok = mg_ota_begin(total_size);
  MG_DEBUG(("%s size %lu, ok: %d", file_name, total_size, ok));
  return ok ? (void *) 1 : NULL;
}
bool glue_ota_end_firmware_update(void *context) {
  mg_timer_add(&g_mgr, 500, 0, (void (*)(void *)) mg_ota_end, context);
  return true;
}
bool glue_ota_write_firmware_update(void *context, void *buf, size_t len) {
  MG_DEBUG(("ctx: %p %p/%lu", context, buf, len));
  return mg_ota_write(buf, len);
}

static struct comms s_comms = {3, "115200", "38400", "AgOpenGPS", 3, 3, "921600", "921600", false, "60ms - F9P", 3, 3, "460800", "0d 0h 0m 0s", 12, "**SSID**", "**PW**", true};
void glue_get_comms(struct comms *data) {
  *data = s_comms;  // Sync with your device
}
void glue_set_comms(struct comms *data) {
  s_comms = *data; // Sync with your device
}

static struct inputs s_inputs = {2, false, 2, false, 50, true, 50, "18", 18, 2, false, 0, "1 - AOG Setting (default)"};
void glue_get_inputs(struct inputs *data) {
  *data = s_inputs;  // Sync with your device
}
void glue_set_inputs(struct inputs *data) {
  s_inputs = *data; // Sync with your device
}

void glue_reply_inputsKickoutModeList(struct mg_connection *c, struct mg_http_message *hm) {
  const char *headers = "Cache-Control: no-cache\r\n" "Content-Type: application/json\r\n";
  const char *value = "[\"1 - AOG Setting (default)\",\"2 - Quadrature Encoder\",\"3 - JD Variable Duty Encoder\",\"4 - WAS-PWM Ratio\",\"5 - Encoder Speed\"]";
  (void) hm;
  mg_http_reply(c, 200, headers, "%s\n", value);
}
static struct outputs s_outputs = {"shoutld change"};
void glue_get_outputs(struct outputs *data) {
  *data = s_outputs;  // Sync with your device
}
void glue_set_outputs(struct outputs *data) {
  s_outputs = *data; // Sync with your device
}

void glue_reply_outputsPwmFreqList(struct mg_connection *c, struct mg_http_message *hm) {
  const char *headers = "Cache-Control: no-cache\r\n" "Content-Type: application/json\r\n";
  const char *value = "[\"122 hz - Valve\",\"490 hz\",\"3921 hz\"]";
  (void) hm;
  mg_http_reply(c, 200, headers, "%s\n", value);
}
static struct misc s_misc = {75, false, "AiO NG v6"};
void glue_get_misc(struct misc *data) {
  *data = s_misc;  // Sync with your device
}
void glue_set_misc(struct misc *data) {
  s_misc = *data; // Sync with your device
}
